name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: yaelahaiz
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add output
          git commit -m "Update contribution snake" || exit 0
          git push
